`define WORD_WIDTH 16
 
`define PHASE_WIDTH 16
 
`define ITERATIONS 16
`define ITERATION_WIDTH 4  // 2^ITERATION_WIDTH = ITERATIONS

`define FIRST_QUADRANT 0
`define SECOND_QUADRANT 90
`define THIRD_QUADRANT 180
`define FORTH_QUADRANT 270